### PR TITLE
Add db connecions, need to finish routing

### PR DESCRIPTION
**Pull request by kjakpan**
May need to separate index.js in Router folder so it's more modularized?

### CODE REVIEW

**Comment by kjakpan** [comment]
It should be listening on port 27017. Remember you need to open two
separate terminal windows and run mongod on one tab then

mongo --host 127.0.0.1:27017


on the other tab. You think I can include this in a script?

**Comment by dlunsfo1** [comment]
Correct.

I think that

/database
/database/index.js will have all db connections
/database/routes
/database/routes/user-api.js then would have the user crud routes

at least that's my thought.

We have to have to parallel paths one that serves the front end which will
use BrowserRouter then the API or database connections would use express
router.

- Daren

**Comment by kjakpan** [comment]
Ohh ok i understand. I'll correct it later. Are we still doing another
stand up tonight

**Comment by dlunsfo1** [comment]
We are. :)

**Pull request merged**
